# Generated by Django 4.0.6 on 2022-07-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='images',
        ),
        migrations.AddField(
            model_name='website',
            name='images',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='website',
            name='urls',
        ),
        migrations.AddField(
            model_name='website',
            name='urls',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
